### ISSUE TITLE
Chat-Processor version request (@oylsister fork)

### ISSUE THREAD

**Issue by Ketz1337** [justinnobledev/custom-chat#1]
Is it possible to request a Chat-Proccesor version of @oylsister's forked plugin?
All plugins on my server use the Chat-Processor plugin so I don't want to disrupt the server with the Simple Chat Processor plugin.

Chat-Processor: https://github.com/drixevel-dev/chat-processor
Fork: https://github.com/oylsister/custom-chat

Thank you in advance for your reply.

**Comment by oylsister** [comment]
> 

My fork is using scp. not CP

**Comment by justinnobledev** [comment]
I'm not sure what @oylsister added in his version of my plugin, but this update was something I meant to do a long time ago and I just kept forgetting to do this. So now I have updated it to use chat-processor over scp and to use `enum struct` over old syntax `enum`. If the fork of this has bug/improvements please feel free to make a merge request or another issue with the requested features.

**Comment by oylsister** [comment]
my version is simply adapted for my own server which also introduce API to set client tag and chat color. And thanks for the update to CP btw
